"""numeric_types_and_constraints

Revision ID: 003973915c99
Revises: bb6739ea6416
Create Date: 2026-04-01 12:35:27.556274

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Identificadores de versión usados por Alembic para encadenar migraciones
revision: str = '003973915c99'
down_revision: Union[str, None] = 'bb6739ea6416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('product_pricing', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price_retail',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cost_supplier',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('restock_alert',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               existing_server_default=sa.text("'5.0'"))

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('price_at_sale',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('cost_at_sale',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_commission',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True,
               existing_server_default=sa.text("'completed'"))

    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_stock_entries_user_id'))

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True,
               existing_server_default=sa.text("'0.0'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (vuelve a la versión anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stocks', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text("'0.0'"))

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_entries_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'completed'"))
        batch_op.alter_column('total_commission',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('cost_at_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price_at_sale',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('restock_alert',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text("'5.0'"))
        batch_op.alter_column('cost_supplier',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price_retail',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('product_pricing', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.drop_table('audit_log')
    # ### end Alembic commands ###
