"""Add StockEntry model

Revision ID: 4251ac7ea290
Revises: 001
Create Date: 2026-03-31 00:00:04.968237

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Identificadores de versión usados por Alembic para encadenar migraciones
revision: str = '4251ac7ea290'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_entries_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('product_pricing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_pricing_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (vuelve a la versión anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_pricing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_pricing_id'))

    with op.batch_alter_table('stock_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_entries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_stock_entries_id'))

    op.drop_table('stock_entries')
    # ### end Alembic commands ###
