"""Add StockEntry model

Revision ID: 433d799e30f2
Revises: 4251ac7ea290
Create Date: 2026-03-31 00:00:10.914866

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Identificadores de versión usados por Alembic para encadenar migraciones
revision: str = '433d799e30f2'
down_revision: Union[str, None] = '4251ac7ea290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (vuelve a la versión anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
