"""add_amortization_fields

Revision ID: 67454e7512f3
Revises: 003973915c99
Create Date: 2026-04-02 00:15:46.106461

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# Identificadores de versión usados por Alembic para encadenar migraciones
revision: str = '67454e7512f3'
down_revision: Union[str, None] = '003973915c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amortization_status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('merr_authorized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proof_filename', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('amortized_to_merr', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_amortization_status'), ['amortization_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios (vuelve a la versión anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_amortization_status'))
        batch_op.drop_column('amortized_to_merr')
        batch_op.drop_column('proof_filename')
        batch_op.drop_column('merr_authorized')
        batch_op.drop_column('amortization_status')

    # ### end Alembic commands ###
